ProjectAmur/ProjectAmur/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;
using ProjectAmur.Controllers.Helpers;
using ProjectAmur.Models;
using WebGrease.Css.Extensions;

namespace ProjectAmur.Controllers
{
    public class CategoriesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Index()
        {
            var categories = db.Categories.Include(c => c.ParentCategory).Where(el=>el.Actual && el.Visible);//подсоединяем подкатегории
            //ViewBag.CatigoriesIncome  = ;
            Dictionary<Category, Double> CatigoriesIncome = new Dictionary<Category, double>();
            foreach(var category in categories)
            {
                double? sum=0;
                var category1 = category;
                foreach(var food in db.Foods.Include(el => el.Category).Include(el => el.PriceWidths).Where(food => food.Actual && food.Visible && food.CategoryId == category1.Id))
                { 
                        var s = db.Invoises.ToList().Where(inv =>inv!=null && inv.FoodId!=null && inv.FoodId == food.Id)?.Where(foodEl => foodEl.PriceWidth!=null && foodEl.PriceWidth.Price != null && foodEl.PriceWidth.Actual)?.Select(inv => inv.PriceWidth.Price).Sum();
                    if(s != null)
                    {
                        sum += (double)s;
                    }
                    
                }
                CatigoriesIncome.Add(category1, Convert.ToDouble(sum));
            }
            return View(CatigoriesIncome);
        }

        // GET: Categories/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.Include(el=>el.ParentCategory).FirstAsync(el=>el.Id==id);

            if (category == null)
            {
                return HttpNotFound();
            }

            //category.ImagePath = Path.GetFileName( category.ImagePath );
            return View( category );
           
        }

        [Authorize(Roles = "Administrator")]
        // GET: Categories/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Title");
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Create(Category category)
        {
            if(category.Title != null)
            {
                var helper = new ModelCafeHelper.CategoryHelper();
                /*await*/
                helper.AddCategory(category, Server);

                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Title", category.CategoryId);
            return View(category);
        }

        [Authorize(Roles = "Administrator")]
        // GET: Categories/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
           
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.Include("ParentCategory").FirstOrDefaultAsync(el=>el.Id==id);
            if (category == null)
            {
           // category.
                return HttpNotFound();
            }

            //category.ImagePath =category.ImagePath;
          ViewBag.CategoryId = new SelectList(db.Categories.ToList(), "Id", "Title", category.CategoryId);
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                category.Actual = true;
                category.Visible = true;
                var helper = new ModelCafeHelper();
                if (String.IsNullOrEmpty(category.ImagePath))
                {
                    category.ImagePath = helper.GetAndSaveImageOnServer(category.ImageFile.First(), Server,
                        "~/Images/Category/");
                }
                db.Entry(category).State = EntityState.Modified;
                await db.SaveChangesAsync();


                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList( db.Categories, "Id", "Title", category.CategoryId );
            return View( category );
           
        }

        [Authorize(Roles = "Administrator")]
        // GET: Categories/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = await db.Categories.FindAsync(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            category.Actual = false;
            db.Entry(category).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Category category = await db.Categories.FindAsync(id);
            List<Category> subCategory = db.Categories.Where(el => el.CategoryId == category.Id).ToList();//Категории, которые являются детьми той, которую удаляем
            List<Food> foods = db.Foods.Where(el => el.CategoryId == id).ToList();//Ещим блюда,которые находятся в этой категории

            subCategory.ForEach(el=>el.CategoryId=null);//Уничтажаем ссылки на вторичные ключи вложенных категорий
            foods.ForEach( el => el.CategoryId = null );//Уничтажаем ссылки на родительскую категорию у всех блюд

            db.Categories.Remove(category);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectAmur/ProjectAmur/Views/Categories/Create.cshtml
@using ProjectAmur.Models
@model ProjectAmur.Models.Category

@{
    ViewBag.Title = "Создание категории";
}



@*@using (Html.BeginForm())
    {*@
<script src="/Scripts/jquery-2.1.4.intellisense.js" type="text/javascript"></script>
<script src="/Scripts/jquery-2.1.4.js" type="text/javascript"></script>
<script src="/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
<script src="/Scripts/jquery.js" type="text/javascript"></script>
<script src="/Scripts/jquery.validate.min.js" type="text/javascript"></script>
<script src="/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
<script src="/Scripts/forAddAreaPrice.js" type="text/javascript"></script>

<link rel="stylesheet" type="text/css" href="/semantic-ui/semantic.min.css">
<script src="/semantic-ui/semantic.min.js"></script>

@using(Html.BeginForm("Create", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    @*<div class="form-horizontal">*@
    <hr />

    <div class="ui raised very padded text container segment">


        <table class="ui very basic collapsing celled table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    @Html.LabelFor(model=>model.Title, htmlAttributes: new
                    {
                        @class = ""
                    })
                </td>
                <td>
                    <div class="ui input">
                        @Html.ValidationSummary(true, "", new
                        {
                            @class = "text-danger"
                        })
                        @Html.EditorFor(model=>model.Title, new
                        {
                            htmlAttributes = new
                            {
                                @class = ""
                            }
                        })
                        @Html.ValidationMessageFor(model=>model.Title, "", new
                        {
                            @class = "text-danger"
                        })
                    </div>
                </td>
            </tr>

            <tr>
                <td>
                </td>
                <td>
                    <div class="ui input">
                        <input type="checkbox" id="DiscountBool" name="DiscountBool" value="true" checked="checked"/>
                        <label style="color: #000;" for="DiscountBool">Скидка для блюд этой категории</label>
                    </div>
                </td>
            </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "" })
                    </td>
                    <td>
                        <div class="ui input">
                           
                            @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "" } })
                        </div>
                    </td>
                </tr>
        
                <tr>
                    <td>
                        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new
                   {
                       @class = "control-label col-md-2"
                   })
                    </td>
                    <td>
                        <div class="ui input">
                            @*@Html.EditorFor( m => m.ImageFile, new { htmlAttributes = new { @class = "form-control" } } )*@
                            @Html.TextBoxFor(m => m.ImageFile, new
                       {
                           @class = "form-control",
                           type = "file"
                       })
                            @Html.ValidationMessageFor(model => model.ImageFile, "", new
                       {
                           @class = "text-danger"
                       })
                        </div>
                    </td>
                </tr>
            <tr>
                <td>
                    @Html.LabelFor(model=>model.Description, htmlAttributes: new
                    {
                        @class = "control-label col-md-2"
                    })
                </td>
                <td>
                    <div class="ui input">
                        @Html.TextAreaFor(model=>model.Description, new
                        {
                            htmlAttributes = new
                            {
                                @class = "form-control"
                            }
                        })
                        @Html.ValidationMessageFor(model=>model.Description, "", new
                        {
                            @class = "text-danger"
                        })
                    </div>
                </td>
            </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.CategoryId)
                    </td>
                    <td>
                        <div class="ui input">
                                @Html.DropDownListFor(fod => fod.CategoryId, (SelectList)ViewBag.CategoryId, htmlAttributes: new { @class = "browser-default" }, optionLabel: "---")
                            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                        </div>

                    </td>
                </tr>
              
            </tbody>
        </table>
        @*</div>*@


        <a href="/../Categories/index" class="negative ui button"><i class="mdi-content-reply left"></i>Отмена</a> 
            <input type="submit" value="Создать" class="positive ui button"> 
    </div>


}

ProjectAmur/ProjectAmur/Views/Categories/Delete.cshtml
@model ProjectAmur.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Удалить</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        @Html.ActionLink( "Назад к списку категорий", "Index" )
    </div>
}

 
<hr/>
<h5>Вы действительно хотите удалить эту категорию?</h5>
<h5>Если эта категория содиржит вложенные категории или блюда, то они будут сохранены</h5>
<div>
    <h4>Категория</h4>
    <hr />
    <table class="striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ParentCategory.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
        <tr>

            <td>
                @Html.DisplayFor(model => model.ParentCategory.Title)
            </td>
            <td>
                @Html.DisplayFor(model => model.ImagePath)
            </td>

            <td>
                @Html.DisplayFor(model => model.Title)
            </td>
            <td>
                @Html.DisplayFor(model => model.Description)
            </td>
        </tr>
      

    </table>

</div>

ProjectAmur/ProjectAmur/Views/Categories/Details.cshtml
@model ProjectAmur.Models.Category

@{
    ViewBag.Title = "Детали";
}

<h2>Детали</h2>
<div>
    @Html.ActionLink( "Изменить", "Edit", new { id = Model.Id } ) |
    @Html.ActionLink( "Назад к списку категорий", "Index" )
</div>
<hr/>

<div>
    <h4>Категория</h4>
    <hr />
    <table class="striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ParentCategory.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
        </tr>
        <tr>

            <td>
                @Html.DisplayFor(model => model.ParentCategory.Title)
            </td>
            <td >
                @{
                    if (@Model.ImagePath != "")
                    {
                            <img width="30%" height="30%" valign="top" style="overflow: auto;" src="@Model.ImagePath" alt="" class="iconimage" />
                            @*@Html.DisplayFor( model => model.ImagePath )*@
                    }
                }
            </td>

            <td>
                @Html.DisplayFor(model => model.Title)
            </td>
            <td>
                @Html.DisplayFor(model => model.Description)
            </td>
        </tr>


    </table>
       
       
 
</div>

ProjectAmur/ProjectAmur/Views/Categories/Edit.cshtml
@using ProjectAmur.Models
@model ProjectAmur.Models.Category

@{
    ViewBag.Title = "Создание категории";
}



@*@using (Html.BeginForm())
    {*@
<script src="/Scripts/jquery-2.1.4.intellisense.js" type="text/javascript"></script>
<script src="/Scripts/jquery-2.1.4.js" type="text/javascript"></script>
<script src="/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
<script src="/Scripts/jquery.js" type="text/javascript"></script>
<script src="/Scripts/jquery.validate.min.js" type="text/javascript"></script>
<script src="/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
<script src="/Scripts/forAddAreaPrice.js" type="text/javascript"></script>

<link rel="stylesheet" type="text/css" href="/semantic-ui/semantic.min.css">
<script src="/semantic-ui/semantic.min.js"></script>

@using(Html.BeginForm("Edit", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()

    @*<div class="form-horizontal">*@
    <hr />

    <div class="ui raised very padded text container segment">


        <table class="ui very basic collapsing celled table">
            <thead>
                <tr>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Title, htmlAttributes: new
               {
                   @class = ""
               })
                    </td>
                    <td>
                        <div class="ui input">
                            @Html.ValidationSummary(true, "", new
                   {
                       @class = "text-danger"
                   })
                            @Html.EditorFor(model => model.Title, new
                   {
                       htmlAttributes = new
                       {
                           @class = ""
                       }
                   })
                            @Html.ValidationMessageFor(model => model.Title, "", new
                   {
                       @class = "text-danger"
                   })
                        </div>
                    </td>
                </tr>

                <tr>
                    <td></td>
                    <td>
                        <div class="ui input">
                            <input type="checkbox" id="DiscountBool" name="DiscountBool" value="true" checked="checked" />
                            <label style="color: #000;" for="DiscountBool">Скидка для блюд этой категории</label>
                        </div>
                    </td>
                </tr>
                <tr  id="DiscountRow">
                    <td>
                        @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "" })
                    </td>
                    <td>
                        <div class="ui input">

                            @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "" } })
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.ImageFile, htmlAttributes: new
                   {
                       @class = "control-label col-md-2"
                   })
                    </td>
                    <td>
                        <div class="ui input">
                            @if(!string.IsNullOrEmpty(Model.ImagePath))
                            { <div class="form-group">
                                <div class="col-md-10">
                                    <img width="50px" height="50px" src="@Model.ImagePath" alt="" class="iconimage" />
                                    @Html.EditorFor(el => Model.ImagePath, new { htmlAttributes = new { @type = "hidden" } }) @*Храним путь к изображению*@
                                </div>
                            </div>
                            }
                            <p>Загрузить новое изображение</p> @*@Html.LabelFor( model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" } )*@
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.ImageFile, new { type = "file" })
                                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        @Html.LabelFor(model => model.Description, htmlAttributes: new
               {
                   @class = "control-label col-md-2"
               })
                    </td>
                    <td>
                        <div class="ui input">
                            @Html.TextAreaFor(model => model.Description, new
                   {
                       htmlAttributes = new
                       {
                           @class = "form-control"
                       }
                   })
                            @Html.ValidationMessageFor(model => model.Description, "", new
                   {
                       @class = "text-danger"
                   })
                        </div>
                    </td>
                </tr>

                <tr>
                    <td>
                        @Html.LabelFor(model => model.CategoryId)
                    </td>
                    <td>
                        <div class="ui input">
                            @Html.DropDownListFor(fod => fod.CategoryId, (SelectList)ViewBag.CategoryId, htmlAttributes: new { @class = "browser-default" }, optionLabel: "---")
                            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                        </div>

                    </td>
                </tr>

            </tbody>
        </table>
        @*</div>*@


        <a href="/../Categories/index" class="negative ui button"><i class="mdi-content-reply left"></i>Отмена</a>
        <input type="submit" value="Сохранить изменения" class="positive ui button">
    </div>


}

<script>
//Меняем у чекбокса значение Value, а так же прячем или отображаем поле для ввода скидки. При скрытии устанавливаем 0, при отображении возвращаем
    $("#DiscountBool").click(function() {
        var prewVal = 0;
        if ($("#DiscountBool").attr("value") === "true") {
            $("#DiscountBool").attr("value", false);
            prewVal = $("#Discount").val("0");
            $("#Discount").val();
            $("#DiscountRow").hide();

        } else if ($("#DiscountBool").attr("value") === "false") {
            $("#DiscountBool").attr("value", true);
            $("#Discount").val(prewVal);
            $("#DiscountRow").show();
        }
    });
</script>

ProjectAmur/ProjectAmur/Views/Categories/Index.cshtml
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-touch.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular-animate.js"></script>
<script src="http://ui-grid.info/docs/grunt-scripts/csv.js"></script>
<script src="http://ui-grid.info/docs/grunt-scripts/pdfmake.js"></script>
<script src="http://ui-grid.info/docs/grunt-scripts/vfs_fonts.js"></script>
<script src="http://ui-grid.info/release/ui-grid.js"></script>
<link rel="stylesheet" href="http://ui-grid.info/release/ui-grid.css" type="text/css">
<script src="~/Scripts/linq.min.js"></script>

<div ng-app="app" ng-controller="MainCtrl">
    <a class="ui primary button" href="/Categories/Create">Создать</a>
    <hr />
    <div id="grid1" ui-grid="gridOptions" ui-grid-grouping class="grid"></div>
</div>



<script>
    var app = angular.module('app', ['ngAnimate', 'ngTouch', 'ui.grid', 'ui.grid.grouping']);

    app.controller('MainCtrl', ['$scope', '$http', '$interval', 'uiGridGroupingConstants', function ($scope, $http, $interval, uiGridGroupingConstants) {

        $scope.gridOptions = {
            columnDefs: [
              { field: 'Категория', displayName: 'Категория' },
                     { field: 'ПроцентСкидки', displayName: 'Процент скидки' },
              { field: 'Доход', displayName: 'Доход' },
              { field: 'РодительскаяКатегория', displayName: 'Родительская категория' },
            { field: 'Изображение', displayName: 'Изображение', cellTemplate: '<div class="ui-grid-cell-contents"><img  alt="изображения нет" ng-src=\"{{grid.getCellValue(row, col)}}\" lazy-src></div>' },
                { name: 'edit', displayName: '', cellTemplate: '<a href="Edit/{{grid.getCellValue(row, col)}}" >Изменить</a> ' }// cellTemplate: '<button id="editBtn" type="button" class="btn-small" ng-click="edit(row.entity)" >{{grid.appScope.f}}</button> ' }
            ]
        };

        $scope.f = "sdfsdf";
        $scope.myData = [];


        $http({
            url: '/api/AdminApi/GetCategories',//'projecamur.amoryakov.ru/api/AdminApi/GetFoods',
            method: "GET"
        }).success(function (data) { //Подулючаемся
            Enumerable.From(data).ForEach(function (el) {
                $scope.myData.push(
                    {
                        "Id": el.CategoryID,
                        "Категория": el.CategoryTitle,
                        "ПроцентСкидки": el.Discount,
                        "Доход": el.Income,
                        "РодительскаяКатегория": el.ParentCategory.CategoryTitle,
                        "Изображение": el.ImagePath,
                        "edit": el.CategoryID
                    }
                );
            });

            $scope.gridOptions.data = $scope.myData;
        });

    }]);
</script>